// <auto-generated />
using Dictionary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dictionary.Migrations
{
    [DbContext(typeof(WordDbContext))]
    partial class WordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dictionary.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EndLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("Length")
                        .HasColumnType("smallint");

                    b.Property<string>("StartLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("WordW")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Length");

                    b.HasIndex("StartLetter");

                    b.HasIndex("WordW")
                        .IsUnique()
                        .HasFilter("[WordW] IS NOT NULL");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
